### ISSUE TITLE
Explore types of function arguments

### ISSUE THREAD

**Issue by deb-sandeep** [deb-sandeep/PyLearn#1]
Refer to the tutorial [Function Tutorial](http://www.tutorialspoint.com/python/python_functions.htm). Go to the Function Arguments section where the following four types of function arguments are explained:
- Required arguments
- Keyword arguments
- Default arguments
- Variable-length arguments

Write a function for each type of function arguments in the `01-Functions/fn_arguments.py` script.

**Comment by argho94** [comment]
Done
